version: "0.2"
words:
  - APPSIGNAL
  - esbenp
  - iife
  - openapi
  - preinstall
  - prestart
  - remle
  - ryanluker
  - skiffa
  - todos
useGitignore: true
files:
  - "**"
enableFiletypes:
  - "*"
