on:
  pull_request: {}

jobs:
  formatting:
    runs-on: ubuntu-latest
    container: node:22.6.0-alpine3.19
    steps:
      - run: apk add make
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run formatting

  spelling:
    runs-on: ubuntu-latest
    container: node:22.6.0-alpine3.19
    steps:
      - run: apk add make
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run spelling
