on:
  pull_request: {}

jobs:
  audit:
    runs-on: ubuntu-latest
    container: node:22.6.0-alpine3.19
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm --workspaces audit --audit-level high

  test:
    runs-on: ubuntu-latest
    container: node:22.6.0-alpine3.19
    steps:
      - run: corepack enable

      - uses: actions/checkout@v4
      - run: npm --no-workspaces ci
      - run: npm run generate
      - run: npm --workspaces ci
      - run: npm --workspaces test
